#!/usr/bin/env bash

#echo "Fetching cosmos address..."
#dfx canister call cosmos_wallet address '()'

echo "Fetching latest blockhash..."
dfx canister call cosmos_rpc cos_getLatestBlockhash '(variant {Mainnet})'

echo "Fetching balance..."
dfx canister call cosmos_rpc cos_getBalance '("devnet","AAAAUrmaZWvna6vHndc5LoVWUBmnj9sjxnvPz5U3qZGY")'

echo "Fetching token balance..."
dfx canister call cosmos_rpc cos_getTokenBalance '("devnet","GeDhDhMT8Cw4hi1vJyRtU9wqWBXURchDoZxttBfFKq9r")'

echo "Fetching account info..."
dfx canister call cosmos_rpc cos_getAccountInfo '("devnet","GeDhDhMT8Cw4hi1vJyRtU9wqWBXURchDoZxttBfFKq9r")'

echo "Fetching transaction..."
dfx canister call cosmos_rpc cos_getTransaction '("devnet","1zhKkhptmaKR83DMbn7FuBRZM2mHGgLSFEuAGoocET5wPywH4gy3FktfT8dL3FV4LJct86pBTsTTANv5NvNTAEN")'

echo "Fetching signature status..."
dfx canister call cosmos_rpc cos_getSignatureStatuses '("devnet", ["1zhKkhptmaKR83DMbn7FuBRZM2mHGgLSFEuAGoocET5wPywH4gy3FktfT8dL3FV4LJct86pBTsTTANv5NvNTAEN"])'

echo "Fetching rpc providers..."
dfx canister call cosmos_rpc getProviders '()'

echo "Fetching metrics..."
dfx canister call cosmos_rpc getMetrics '()'

#dfx canister call cosmos_rpc getNodesInSubnet '()'

echo "Done"
